version: '3'

services:
  node0:
    build: .
    image: myblockcoin
    ports:
      - '10000:10000'
    environment:
      PEERS: 'node1,node2'
      BANK_ID: 0

  node1:
    image: myblockcoin
    ports:
      - '10001:10000'
    environment:
      PEERS: 'node0,node2'
      BANK_ID: 1

  node2:
    image: myblockcoin
    ports:
      - '10002:10000'
    environment:
      PEERS: 'node0,node1'
      BANK_ID: 2
